### ISSUE TITLE
Incompatible with Windows due to UnicodeDecodeError: 'charmap' codec can't decode byte in position: character maps to <undefined>

### ISSUE THREAD

**Issue by sgbaird** [comaniac/latex-proj-tool#1]
```python
(latexdiff) PS C:\Users\sterg\Documents\overleaf\discover-paper-dd-initial> python -m latex_proj_tool flat --output old.tex main.tex
[2021-11-30 20:54:27]    INFO TexFlatter: Visit main.tex
[2021-11-30 20:54:27]    INFO TexFlatter: Visit values.tex
[2021-11-30 20:54:27]    INFO TexFlatter: Visit values/numbers.tex
[2021-11-30 20:54:27]    INFO TexFlatter: Visit values/words.tex
[2021-11-30 20:54:27]    INFO TexFlatter: Visit abbrev.tex
[2021-11-30 20:54:27]    INFO TexFlatter: Visit authors.tex
Traceback (most recent call last):
  File "C:\Users\sterg\Miniconda3\envs\latexdiff\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sterg\Miniconda3\envs\latexdiff\lib\runpy.py", line 87, in _run_code    exec(code, run_globals)
  File "C:\Users\sterg\Miniconda3\envs\latexdiff\lib\site-packages\latex_proj_tool\__main__.py", line 79, in <module>     
    main()
  File "C:\Users\sterg\Miniconda3\envs\latexdiff\lib\site-packages\latex_proj_tool\__main__.py", line 71, in main
    tools.TexFlatter(config.root, config.output).run()
  File "C:\Users\sterg\Miniconda3\envs\latexdiff\lib\site-packages\latex_proj_tool\tools.py", line 103, in run    self.visit(self.root_file_name)
  File "C:\Users\sterg\Miniconda3\envs\latexdiff\lib\site-packages\latex_proj_tool\tools.py", line 61, in visit
    for line in tex_file:
  File "C:\Users\sterg\Miniconda3\envs\latexdiff\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3513: character maps to <undefined>
```

**Comment by sgbaird** [comment]
Related:
https://stackoverflow.com/questions/42019117/unicodedecodeerror-charmap-codec-cant-decode-byte-0x8f-in-position-xxx-char

**Comment by sgbaird** [comment]
Additionally, if using WSL on Windows as a workaround with a conda environment, use `python==3.8` instead of `3.9`. See https://github.com/microsoft/WSL/issues/4020

**Comment by comaniac** [comment]
Thanks for reporting and the investigation! I don't use Windows  very often so don't realize this issue. When I got time, I'll try to setup a CI on Windows environment and see how this issue should be resolved in a general way. You are also welcome to send PRs if you got a solution :)

**Comment by sgbaird** [comment]
For reference, I was able to get this work on WSL (Windows Subsystem for Linux) with the workaround I mentioned and using the instructions from the README. The results were very satisfying 😄. Awesome "track changes"-like way to address reviewer comments and mark the changes without having to modify the way I like to organize my LaTeX projects (many files, subdirectories, etc.). Thank you for the tool!

**Comment by comaniac** [comment]
Thanks for the insight! You could send a PR for the workaround if you're willing to :)
